use_frameworks!

platform :ios, '8.0'

target 'UCRuntimeKit_Example' do
  pod 'UCRuntimeKit', :path => '../'

  target 'UCRuntimeKit_Tests' do
    inherit! :search_paths

#    pod 'Specta'
#    pod 'Expecta'
#    pod 'FBSnapshotTestCase'
#    pod 'Expecta+Snapshots'
  end
end
